apiVersion: apps/v1
kind: Deployment
metadata:
    name: conuhacks-api
    labels:
        app: conuhacks-api
        version: '1'
spec:
    replicas: 1
    selector:
        matchLabels:
            app: conuhacks-api
            version: '1'
    template:
        metadata:
            labels:
                app: conuhacks-api
                version: '1'
        spec:
            containers:
                - name: conuhacks-api
                  image: joeyzhou98/foodbook:1.0
                  imagePullPolicy: Always
                  resources:
                        requests:
                            cpu: "0.25"
                            memory: "256Mi"
                        limits:
                            cpu: "1"
                            memory: "512Mi"
                  ports:
                    - name: http-traffic
                      containerPort: 5000
                      protocol: TCP